spring:
  application:
    name: walldeal-web-service
  profiles:
    active: localhost
  main:
    allow-bean-definition-overriding: true
info:
  component: WallDeal Web Service

---

spring:
  config:
    activate:
      on-profile: localhost
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: DEBUG

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: stage

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.application.name}:${random.uuid}
