spring:
  datasource:
    url: jdbc:postgresql://walldeal.c1cye4oyo8y7.eu-north-1.rds.amazonaws.com:5432/walldeal
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: walldeal-web-service
    profiles:
      active: localhost
    main:
      allow-bean-definition-overriding: true
info:
  component: WallDeal Web Service
---

spring:
  cache:
    type: redis
    data:
      redis:
        host: localhost
        port: 6379
  config:
    activate:
      on-profile: localhost

server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security: DEBUG

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

---
spring:
  main:
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: stage
  cache:
    type: redis
    data:
      redis:
        host: redis
        port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.application.name}:${random.uuid}