version: '3.3'

services:
  api-gateway:
    hostname: api-gateway
    image: wdapigateway.azurecr.io/api-gateway:latest
    networks:
      - web-service-network-backend
    expose:
      - 8762
    ports:
      - 8762:8762
    environment:
      - "SPRING_PROFILES_ACTIVE=stage"
    entrypoint: ["java","-jar","app.jar"]

networks:
  web-service-network-backend: