spring:
  application:
    name: walldeal-cache-service
  profiles:
    active: localhost

  main:
    allow-bean-definition-overriding: true
info:
  component: WallDeal Cache Service
logging:
  level:
    root:
    com.whisper: DEBUG
server:
  port: 9791

---
spring:
  config:
    activate:
      on-profile: localhost
  cache:
    type: redis
    data:
      redis:
        host: localhost
        port: 6379

feign:
  walldeal-web-service:
    name: walldeal-web-service
    url: http://localhost:8762

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10

---
spring:
  config:
    activate:
      on-profile: stage
  cache:
    type: redis
  data:
    redis:
      host: redis
      port: 6379

feign:
  walldeal-web-service:
    name: walldeal-web-service
    url: http://api-gateway:8762

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10